### ISSUE TITLE
一直显示加载中。

### ISSUE THREAD

**Issue by sai2333** [moedong/vue-wfcast#1]
XMLHttpRequest cannot load https://www.weaoo.com/weaoo.php?a=searchAreas&v=%E5%B9%BF%E5%B7%9E.每次进入都是正在加载。想问下作者用的是什么API？

**Comment by moedong** [comment]
http://www.weaoo.com 域名是不能直接访问的，因此 在 config/index.js  设置了代理

 dev: {
    env: require('./dev.env'),
    port: 8080,
    autoOpenBrowser: true,
    assetsSubDirectory: 'static',
    assetsPublicPath: '/',
    proxyTable: {
      ...
      '/weaoo': {
        target: 'http://www.weaoo.com',
        changeOrigin: true,
        pathRewrite: {
          '^/weaoo': ''
        }
      }
    }
    ...
